# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    rate_limiter:
        api_general:
            interval: '1 minute'
            limit: 60
            policy: sliding_window

    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@prod:
    framework:
        session:
            enabled: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
